import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

interface Doan {
  message: string;
  price: string;
}

const Home: NextPage = () => {
  const [message, setMessage] = useState("");
  const [price, setPrice] = useState("");

  const [warehouse, setWarehouse] = useState<Doan[]>([]);

  function handleShow() {
    setWarehouse([...warehouse, { message, price }]);
  }
  console.log(warehouse);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <input
            style={{ margin: 30 }}
            type="text"
            value={message}
            onChange={(e) => setMessage(e.target.value)}
          />
          <input
            style={{ margin: 30 }}
            type="text"
            value={price}
            onChange={(e) => setPrice(e.target.value)}
          />
          <br />
          <button onClick={handleShow}>Click</button>
          {warehouse.map((e: Doan, i: number) => (
            <li key={i} style={{ marginTop: 100 }}>
              {e.message}-{e.price}
            </li>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
